<?php

/**
 * @file
 * The GDG Group Login Module.
 *
 * Redirects user to their first group home page upon login.
 */

/**
 * Implementation of hook_user_login().
 */
function gdg_group_login_user_login(&$edit, $account) {

  $redirect = _gdg_group_login_redirect_location($account);

  // Unless there is already a redirection going, or the user is trying to reset
  // his or her password, we redirect to $redirect.
  if (empty($_GET['destination'])
    && !is_null($redirect)
    && (!isset($_POST['form_id']) || $_POST['form_id'] != 'user_pass_reset')) {
    $_GET['destination'] = $redirect;
  }

}


/**
 * Get the redirection location.
 *
 * @param stdClass $account
 *   The user account.
 *
 * @return string
 *   The path to which to redirect.
 */
function _gdg_group_login_redirect_location($account) {

  // Retrieve all active memberships.
  if ($memberships = GroupMembership::getByActiveStatus($account->uid)) {
    $first = array_shift($memberships);
    $redirect = 'group/' . $first->gid;
    return $redirect;
  }

}
