; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.50"

; Modules
projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc5"

projects[adminrole][subdir] = "contrib"
projects[adminrole][version] = "1.1"

projects[backup_migrate][subdir] = "contrib"
projects[backup_migrate][version] = "3.1"

projects[better_formats][subdir] = "contrib"
projects[better_formats][version] = "1.0-beta2"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.10"

projects[date][subdir] = "contrib"
projects[date][version] = "2.9"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.5"

projects[diff][subdir] = "contrib"
projects[diff][version] = "3.2"

projects[ds][subdir] = "contrib"
projects[ds][version] = "2.14"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.7"

projects[entityreference][subdir] = "contrib"
projects[entityreference][version] = "1.1"

projects[features][subdir] = "contrib"
projects[features][version] = "2.10"

projects[field_group][subdir] = "contrib"
projects[field_group][version] = "1.5"

projects[file_entity][subdir] = "contrib"
projects[file_entity][version] = "2.0-beta3"

projects[globalredirect][subdir] = "contrib"
projects[globalredirect][version] = "1.5"

projects[google_analytics][subdir] = "contrib"
projects[google_analytics][version] = "2.3"

projects[group][subdir] = "contrib"
projects[group][version] = "1.x-dev"

projects[imagecache_token][subdir] = "contrib"
projects[imagecache_token][version] = "1.0-rc2"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.7"

projects[invite][subdir] = "contrib"
projects[invite][version] = "4.0-beta2"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.3"

projects[lightbox2][subdir] = "contrib"
projects[lightbox2][version] = "1.0-beta1"

projects[link][subdir] = "contrib"
projects[link][version] = "1.4"

projects[logintoboggan][subdir] = "contrib"
projects[logintoboggan][version] = "1.5"

projects[master][subdir] = "contrib"
projects[master][version] = "2.0-beta4"

projects[media][subdir] = "contrib"
projects[media][version] = "2.0-beta2"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "2.0"

projects[multiform][subdir] = "contrib"
projects[multiform][version] = "1.1"

projects[nice_menus][subdir] = "contrib"
projects[nice_menus][version] = "2.5"

projects[noindex_external_links][subdir] = "contrib"
projects[noindex_external_links][version] = "2.0-rc1"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.3"

projects[plupload][subdir] = "contrib"
projects[plupload][version] = "1.7"

projects[redirect][subdir] = "contrib"
projects[redirect][version] = "1.0-rc3"

projects[stage_file_proxy][subdir] = "contrib"
projects[stage_file_proxy][version] = "1.7"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[subpathauto][subdir] = "contrib"
projects[subpathauto][version] = "1.3"

projects[taxonomy_menu][subdir] = "contrib"
projects[taxonomy_menu][version] = "1.5"

projects[token][subdir] = "contrib"
projects[token][version] = "1.6"

projects[video_embed_field][subdir] = "contrib"
projects[video_embed_field][version] = "2.0-beta11"

projects[views][subdir] = "contrib"
projects[views][version] = "3.14"

projects[wysiwyg][subdir] = "contrib"
projects[wysiwyg][version] = "2.2"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.

projects[ldstabs][download][type] = ""
projects[ldstabs][download][url] = ""
projects[ldstabs][type] = "theme"
projects[ldstabs][subdir] = "custom"

projects[bootstrap][subdir] = "contrib"
projects[bootstrap][version] = "3.6"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"
